### ISSUE TITLE
data:rollback fails depending on order of data and schema migrations

### ISSUE THREAD

**Issue by panpsonis** [ilyakatz/data-migrate#89] opened 2018-05-31 13:30 UTC
I run into the following issue:
When the order of data and schema migrations (based on filename) is intermixed, I cannot do a data:rollback if there are schema migrations in between the current and previous data migration.

Consider the following output of `db:migrate:status:with_data`
 ```
Status    Type    Migration ID   Migration Name
------------------------------------------------------------
   up     schema  20160517153654  Create links
   up     schema  20160517153831  Create assets
   up     schema  20161202212757  Devise create users
   up      data   20169423231126  Add users
   up      data   20169517225124  Add basic data
   up     schema  20171108210818  Create factions
   up     schema  20171116173510  Create entries
   up      data   20180517231700  Add draw events
```
At this point, I can do a `data:rollback` to revert the latest data migration. However, any further calls to `data:rollback` will silently fail. The overall behavior and log messages are as described in #67 .

I would expect that `data:rollback` would not be affected by schema migration at all. Is this normal?

**Comment by ilyakatz** [comment] 2018-06-13 23:53
hi @panpsonis , would it be possible for you to create a small rails app that reproduces this problem so I can debug this?

**Comment by panpsonis** [comment] 2018-06-23 10:31
Hi @ilyakatz , check this out and let me know if it helps.
https://github.com/panpsonis/data-migrate-issue-89

**Comment by ilyakatz** [comment] 2018-07-07 05:59
hi @panpsonis, thanks for the repro repo. I was able to work on this and identified the problem. See #92. It's a little tricky fixing it given that there is a need for legacy support, but I think I have a decent way to deal with it. Can you check out the PR and let me know if you have any thoughts.

**Comment by raman162** [comment] 2018-08-07 19:45
Hello @ilyakatz I encountered the same issue and I can report that #92 will solve the problem. The issue seems to be because of the class `get_all_versions` method which I see has been changed. Any update on when this PR will be merged in. I would be glad to help in anyway possible to speed up the process so I can begin working on the library myself.

**Closed** 2018-08-19 22:57 UTC

**Comment by ilyakatz** [comment] 2018-08-20 00:12
@raman162 i merged it in. can you see if it works well for you?
